name = "nullchat-signaling"
main = "index.js"
compatibility_date = "2024-01-01"

[[durable_objects.bindings]]
name = "PEER_SESSION"
class_name = "PeerSession"

[[migrations]]
tag = "v3"
new_sqlite_classes = ["PeerSession"]
